### ISSUE TITLE
关于RS-SD推理时，1p和20p模型的代码不一致问题

### ISSUE THREAD

**Issue by jaycecd** [om-ai-lab/RS5M#16]
您好，请问我在使用RS-SD推理时，按您在hugging face中的提示，使用了[Dreambooth](https://github.com/ShivamShrirao/diffusers/tree/main/examples/dreambooth#inference)中的代码进行了推理：

```python
from diffusers import StableDiffusionPipeline
import torch

model_id = r"F:\huggingface\Zilun\GeoRSSD\checkpoint\20p\22000"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16).to("cuda")

prompt = ["there is an aerial view of some buildings", "an aerial view of the campus and surrounding fields"]
images = pipe(prompt, num_inference_steps=50, guidance_scale=7.5, height=512, width=512).images

for index, image in enumerate(images):
    image.save(prompt[index] + ".png")
```

使用20p模型的时候正常工作了，但是为什么使用1p模型时报错：
```python
OSError: Error no file named scheduler_config.json found in directory F:\huggingface\Zilun\GeoRSSD\checkpoint\1p\18000.
```
具体报错如下：
```python
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2023.3\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2023.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2023.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\Code\Python\Git\kohya_ss\geo_rs_sd.py", line 12, in <module>
    pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16).to("cuda")
  File "D:\Code\Python\Git\kohya_ss\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1105, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "D:\Code\Python\Git\kohya_ss\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 475, in load_sub_model
    loaded_sub_model = load_method(cached_folder, **loading_kwargs)
  File "D:\Code\Python\Git\kohya_ss\venv\lib\site-packages\diffusers\schedulers\scheduling_utils.py", line 140, in from_pretrained
    config, kwargs, commit_hash = cls.load_config(
  File "D:\Code\Python\Git\kohya_ss\venv\lib\site-packages\diffusers\configuration_utils.py", line 364, in load_config
    raise EnvironmentError(
OSError: Error no file named scheduler_config.json found in directory F:\huggingface\Zilun\GeoRSSD\checkpoint\1p\18000.
```
我查看了1p的模型文件夹，下方确实没有`scheduler_config.json`这个文件，而20p的文件夹下方是有这个文件的，请问该如何解决这个问题？您是否能给出您的推理代码？

**Comment by BinSpa** [comment]
您好，感谢您指出这个问题，在此为我们工作的疏忽表示抱歉。现在上传的18000是保存不完整的ckpt，我们将会上传保存完整的ckpt。建议您使用20p的版本，因为效果更好，使用的训练数据更多。

**Comment by jaycecd** [comment]
谢谢~~
